### ISSUE TITLE
Need To Be Able To Add NOAA Sites to Maps

### ISSUE THREAD

**Issue by wekirkco** [MTUHIDE/CoCoTemp#113]
NOAA sites need to be retrieved via their API and be added to both the home page and comparison page, the idea right now is that sites will be added when the user zooms in on the map so that we don't need to GET more than the API limit of 1000.

**Comment by ckpalmer** [comment]
Added in commit : 82d4e39534b0c34eae6907e7be06c5ffb85d0208
