### ISSUE TITLE
User Documentation Help Page

### ISSUE THREAD

**Issue by wekirkco** [MTUHIDE/CoCoTemp#115]
The help page hasn't been updated in a while, the page needs to be updated to reflect changes that have been made since the last update.

**Comment by ckpalmer** [comment]
Add section on setting up the physical site and how to shield the temperature sensor.

**Comment by ckpalmer** [comment]
Look at notes from meeting with ben that Tom berg sent out

**Comment by ckpalmer** [comment]
Finished on commit: 39e42ac165777b163ec9e3e99b90788f3afd331c
