### ISSUE TITLE
Make a presentation to pitch CoCo Temp to investors at NASA

### ISSUE THREAD

**Issue by Viperouskahn** [MTUHIDE/CoCoTemp#148]

**Comment by TomAllenBerg** [comment]
[Here](https://venngage.com/blog/best-pitch-decks/) are some good examples of investor presentations to take inspiration from

**Comment by TomAllenBerg** [comment]
Completed: https://docs.google.com/presentation/d/1FCI5JpCe475vS9nqtfa1ZFNpP_3alsGe2SH_bNosJSU/edit#slide=id.ge9090756a_1_58.
