### ISSUE TITLE
Microclimate page Filter declares 800 < 1000

### ISSUE THREAD

**Issue by ckpalmer** [MTUHIDE/CoCoTemp#176]

**Comment by ckpalmer** [comment]
![bug](https://user-images.githubusercontent.com/43018470/75496280-bb404180-598e-11ea-9c98-d9b044a9d3b0.JPG)

**Comment by abigmyers** [comment]
Fixed in commit: [be956b0](https://github.com/MTUHIDE/CoCoTemp/commit/be956b002ce97656f4c3489917282ff734a04f2a)
