### ISSUE TITLE
Change Confirmation Email 

### ISSUE THREAD

**Issue by TomAllenBerg** [MTUHIDE/CoCoTemp#183]
Change the account confirmation email to reflect a more professional design. Here is the current confirmation email: 
![image](https://user-images.githubusercontent.com/54914160/78956133-59a3e480-7aaf-11ea-89c7-e3c7c47b0d6a.png) Instead it should be changed to look more professional like the examples that can be found [here](https://automizy.com/blog/registration-confirmation-emails/)

**Comment by lnroot** [comment]
Fixed in commit [21da46d](https://github.com/MTUHIDE/CoCoTemp/commit/21da46dbce090361f3bc772b3c2daccc40f74fe2)
