### ISSUE TITLE
Fix Layout Issues on 'Getting Started' Page

### ISSUE THREAD

**Issue by TomAllenBerg** [MTUHIDE/CoCoTemp#186]
There are some issues that need to be fixed with the 'Getting Started' tutorial page. Pictured here is one of them: 
![image](https://user-images.githubusercontent.com/54914160/78960854-54e62d00-7abd-11ea-9825-c57bf1575244.png) The image captions and images are separate and this means with some displays the caption and image are not together. On my laptop the format is skewed to a much greater degree. Instead, HTML has a figcaption option that should be used for the captions for the images. More details on this can be found [here](https://www.w3schools.com/tags/tag_figcaption.asp).

**Comment by zyfers** [comment]
I can have a look. Please assign this to me

**Comment by mace1099** [comment]
Hello Himanshu, this project isn't for open source development. Only members of the Humane Interface Design Enterprise can work on this project.

**Comment by TomAllenBerg** [comment]
Fixed in commit 50014ed855526f47c5f53a8e6c30672e9f28d6f1
