### ISSUE TITLE
Microclimate Infinite Loading Screen

### ISSUE THREAD

**Issue by mace1099** [MTUHIDE/CoCoTemp#188]
If on the micro climate page, after you select a NOAA site and get sites, you then go back and select the blank option above Alabama and hit get sites you will be stuck in an infinite loading screen.

**Comment by abigmyers** [comment]
Fixed in commit [3b0ce40](https://github.com/MTUHIDE/CoCoTemp/commit/3b0ce40fe4b98bbd3b6f934bb29a165923d4c78c)
